### PR TITLE
Update Mongoose and Update Compose steps

### LINKED ISSUE #9: Add option for a mongodb in kubernetes
A MongoDB container in kubernetes is good since `Compose for MongoDB` does not have a lite plan

### LINKED ISSUE #10: Compose for MongoDB and Let's Encrypt Certificates changes
* changes in connection strings
* self-signed certificates are no longer offered and not shown in the IBM Cloud dashboard (now using Let's Encrypt certificate)
  * although, old connection strings and certificates with self-signed certificates should still work

TODO:

- [ ] Update README and code

Source: https://compose.com/articles/mongodb-and-lets-encrypt-certificates/

### PR DESCRIPTION
**Pull request by AnthonyAmanse**
This commit updates the version of mongoose to the current latest (5.2).

This commit also updates the use of Compose for MongoDB. The service is
now using Let's Encrypt certificates. Previously, a provided certificate
was needed to be mounted for connection. The MongoDB URL is now using a
secret in map-api.yaml instead of a plain environment variable.

This commit also adds an alternative to compose. This commit adds a new
yaml file for a MongoDB container in Kubernetes for testing/development.

This commit also moves the yaml files in the manifests folder.

Fixes #9, Fixes #10

Signed-off-by: AnthonyAmanse <ghieamanse@gmail.com>

### CODE REVIEW

**Review by ykoyfman — APPROVED** [review]
Lgtm.  One question: why set           imagePullPolicy: Always ?  I find it more convenient to use ifNotPresent so I can use images already present on system.

**Comment by AnthonyAmanse** [comment]
@ykoyfman I set it to `Always` in development. I almost always push the image with the same name and same tag in development and having it set to `Always` would pull the updated one instead. **(in an IKS context at least)**

For minikube, I can see why it would be good to set it to `ifNotPresent` if I'm using the docker env in minikube's node

**Review by loafyloaf — APPROVED** [review]
lgtm

**Comment by ykoyfman** [comment]
> @ykoyfman I set it to `Always` in development. I almost always push the image with the same name and same tag in development and having it set to `Always` would pull the updated one instead. **(in an IKS context at least)**
> 
> For minikube, I can see why it would be good to set it to `ifNotPresent` if I'm using the docker env in minikube's node

Right, I ran into this when building my own images for OpenLiberty before they were pushed to docker hub, so I changed the yaml files to use ifNotPresent.

**Pull request merged**
